"""
Django settings for Vmmodulares project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from pathlib import Path
from django.templatetags.static import static
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-377*2c9wgqz_dzm&y1(-!f9x7+5^wi_$(@g))$+mk#(-b2jeox'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    'fieldex.up.railway.app', '127.0.0.1',
    'fieldex.com.co', 'www.fieldex.com.co',
]
CSRF_TRUSTED_ORIGINS = ["https://*.up.railway.app", "https://*.fieldex.com.co"]

CORS_ORIGINS_WHITELIST = ["https://fieldex.up.railway.app",
                          "https://fieldex.com.co",
                          "https://www.fieldex.com.co",]
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'import_export',
    'captcha',
    'webpage.apps.WebpageConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'webpage.middleware.MediaFilesMiddleware',  # Agregar nuestro middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Vmmodulares.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'webpage.context_processors.global_context',
                'webpage.context_processors.seo_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Vmmodulares.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
"""
DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_PUBLIC_URL'))
}

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vm_modulares',
        'USER': 'postgres',
        'PASSWORD': 'Sebastyk120',
        'HOST': 'localhost',
        'PORT': '5432',  # Puerto de PostgreSQL
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True

# Media files configuration
MEDIA_URL = '/media/'
if DEBUG:
    # En desarrollo, usar directorio local
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    print(f"DEBUG=True: MEDIA_ROOT = {MEDIA_ROOT}")
else:
    # En producción (Railway), usar el volumen persistente
    MEDIA_ROOT = '/media'
    print(f"DEBUG=False: MEDIA_ROOT = {MEDIA_ROOT}")

# Configuración específica para Railway - eliminar configuración de WhiteNoise para media
if not DEBUG:
    # Solo mantener WhiteNoise para archivos estáticos
    WHITENOISE_STATIC_PREFIX = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CONFIGURACIÓN MAIL:
DEFAULT_FROM_EMAIL = "sebastyk120@gmail.com"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = DEFAULT_FROM_EMAIL

try:
    EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
except KeyError:
    raise ImproperlyConfigured('La variable de entorno EMAIL_HOST_PASSWORD no está definida')

# CONFIGURACIÓN CAPTCHA
CAPTCHA_FONT_SIZE = 30
CAPTCHA_IMAGE_SIZE = (120, 50)
CAPTCHA_LENGTH = 4
CAPTCHA_TIMEOUT = 5  # minutes
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
CAPTCHA_FOREGROUND_COLOR = '#5A2D82'  # Usar el color corporativo
CAPTCHA_NOISE_FUNCTIONS = (
    'captcha.helpers.noise_arcs',
    'captcha.helpers.noise_dots',
)
CAPTCHA_FILTER_FUNCTIONS = (
    'captcha.helpers.post_smooth',
)
CAPTCHA_WORDS_DICTIONARY = '/usr/share/dict/words'
CAPTCHA_FLITE_PATH = None

