# Generated by Django 5.2.5 on 2025-08-22 20:52

import django.db.models.deletion
import webpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='FotosSubcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=webpage.models.upload_to_categoria, verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción de la imagen')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (0 = primera)', verbose_name='Orden')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.subcategoria', verbose_name='subcategoria')),
            ],
            options={
                'verbose_name': 'Foto de Subcategoría',
                'verbose_name_plural': 'Fotos de Subcategorías',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
    ]
