# Generated by Django 5.2.6 on 2025-10-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría de interés')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contacto')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email enviado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha_contacto'],
            },
        ),
    ]
